apiVersion: v1
kind: Service
metadata:
  name: redisinsight-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.redisinsight_port }}
  selector:
    app: redisinsight-{{ .Release.Name }}
  clusterIP: None

